export const TAG_OPTIONS = [
    { text: "高难", value: 1 },
    { text: "PVP", value: 2 },
    { text: "挂机", value: 3 },
    { text: "团队协作", value: 4 },
    { text: "单人作战", value: 5 },
    { text: "副本探险", value: 6 },
    { text: "策略", value: 7 },
    { text: "休闲", value: 8 },
    { text: "成就", value: 9 },
    { text: "挑战", value: 10 },
    { text: "排行榜", value: 11 },
    { text: "掉落", value: 12 },
    { text: "PVE", value: 13 },
    { text: "PVE-困难", value: 14 },
    { text: "极速通关", value: 15 },
    { text: "BOSS战", value: 16 },
    { text: "公会", value: 17 },
    { text: "限时活动", value: 18 },
    { text: "剧情模式", value: 19 },
    { text: "合作", value: 20 },
  ];